#Define a Github workflow to build and test a React app and open issue if tests pass
# Use pull event to trigger workflow
# Use ubuntu latest

name: Build and Test React App, then Open Issue
on: 
  pull_request:
    branches: [ main ]


jobs:
  build:
    runs-on: ubuntu-latest
    # Define steps 
    steps:
      # First step is to checkout code
      - name: Checkout code
        uses: actions/checkout@v3
      # Second step is to install dependencies
      - name: Install dependencies
        run: npm install
      # Third step is to build the app
      - name: Build app
        run: npm run build
      # Fourth step is to run tests
      - name: Run tests
        run: npm run test
      # Fifth step is to open issue using github CLI if tests pass
      - name: Create Issue 
        if: ${{ success() }}
        run: |
          echo "Tests passed"
          gh issue create --title "Tests passed" --body "All tests passed, approve then deploy"
        # env variable
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}